config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins'
  devise_for :users, path: 'users'
  root :to => "home#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :skills
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :skills
  validates :title, :presence => true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :project

  validates :name, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :is_admin?

  def is_admin?
    current_user && current_user.admin
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :only => [:new, :edit] do
  redirect_to new_user_session_path unless current_user && current_user.admin
end
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to "/projects/"
  end

  private
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!, :only => [:new]
  def index
    @skills = Skill.all
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_path
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      redirect_to skills_path
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to "/skills/"
  end

  private
    def skill_params
      params.require(:skill).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>hello</h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-light">
    <div class="container-fluid">
      <div class="navbar-header">
        <h1>Portfolio by Annie Shin</h1>
        <h2>Featuring skills, projects, and hobbies</h2>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <span class="navbar-text">
          <h2><%= link_to "Add New Project", new_project_path %></h2>
        </span>
        <span class="navbar-text">
          <h2><%= link_to "Projects", projects_path %></h2>
        </span>
      </ul>
    </div>
   </nav>
  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= render "layouts/errors", :object => @project %>

<%= form_for @project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit  %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "projects/form" %>

<hr>
<p><%= link_to "Return to projects", projects_path %></p>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li>Title: <%= link_to project.title, project_path(project) %></li>
    <p>Description: <%= project.description %></p>
  <% end %>
</ul>

<hr>

<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for @project do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit  %>
<% end %>

app/views/projects/show.html.erb
<div class="container">

  <h1><%= @project.title %></h1>

  <% if @project.skills.any? %>
    <h4>Here are the skills for this project:</h4>

    <ul>
      <% @project.skills.each do |skill| %>
        <li>
          <%= skill.name %> |
          <%= link_to "Edit", edit_project_skill_path(@project, skill) %> |
          <%= link_to "Delete", project_skill_path(@project, skill),
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no skills yet!</p>
  <% end %>

  <p><%= link_to "Add a skill", new_project_skill_path(@project) %></p>
  <p><%= link_to "Delete List", project_path(@project),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"} %></p>

  <hr>
  <p><%= link_to "Return to projects", projects_path %></p>
</div>

app/views/skills/_form.html.erb
<%= render "layouts/errors", :object => @skill %>

<%= form_for @skill do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit  %>
<% end %>

app/views/skills/edit.html.erb
<h1>Edit Skill</h1>

<%= render "skills/form" %>

<hr>
<p><%= link_to "Return to projects", projects_path %></p>

app/views/skills/index.html.erb
<h1>Skills</h1>

<ul>
  <% @skills.each do |skill| %>
    <li>Skill: <%= link_to skill.name, skill_path(skill) %></li>
    <p>Description: <%= skill.description %></p>
  <% end %>
</ul>

<hr>

<%= link_to "New Skill", new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render "skills/form" %>

<hr>
<p><%= link_to "Return to projects", projects_path %></p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>